import React,{useEffect,useState} from 'react'
import { supabase } from '../../lib/supabase.js'
import { useIsMobile } from '../../hooks/useIsMobile.js'
import { SectionCard,SectionTitle } from '../ui/SectionCard.jsx'
import Input from '../ui/Input.jsx'
import Button from '../ui/Button.jsx'

const TABS=[['summary','Résumé'],['analysis','Analyse'],['presence','Présence numérique'],['opportunities','Opportunités'],['messages','Messages'],['history','Historique'],['notes','Notes']]
const EDIT=['name','category','description','address','city','postal_code','phone','email','website','instagram','linkedin']
const fieldLabel={name:'Entreprise',category:'Catégorie',description:'Description',address:'Adresse',city:'Ville',postal_code:'Code postal',phone:'Téléphone',email:'Email professionnel',website:'Site web',instagram:'Instagram',linkedin:'LinkedIn'}

export default function ProspectDetail({prospect,onUpdate,onRequestAnalysis,onClose,onToast}) {
  const mobile=useIsMobile(),[tab,setTab]=useState('summary'),[form,setForm]=useState(prospect),[related,setRelated]=useState({sources:[],events:[],messages:[]}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[analyzing,setAnalyzing]=useState(false)
  useEffect(()=>setForm(prospect),[prospect])
  useEffect(()=>{let live=true;setLoading(true);Promise.all([
    supabase.from('prospect_sources').select('*').eq('prospect_id',prospect.id).order('fetched_at',{ascending:false}),
    supabase.from('prospect_events').select('*').eq('prospect_id',prospect.id).order('created_at',{ascending:false}),
    supabase.from('prospect_messages').select('*').eq('prospect_id',prospect.id).order('created_at',{ascending:false}),
  ]).then(results=>{if(!live)return;setRelated({sources:results[0].data??[],events:results[1].data??[],messages:results[2].data??[]});setLoading(false)});return()=>{live=false}},[prospect.id,prospect.updated_at])
  const set=(key,value)=>setForm(previous=>({...previous,[key]:value}))
  const save=async patch=>{setSaving(true);const result=await onUpdate(prospect,patch);setSaving(false);if(!result.error)onToast?.('Fiche prospect sauvegardée','success');return result}
  const saveIdentity=()=>save(Object.fromEntries(EDIT.map(key=>[key,form[key]||null])))
  const analyze=async()=>{setAnalyzing(true);const result=await onRequestAnalysis(prospect.id);setAnalyzing(false);onToast?.(result.error||'Analyse ajoutée à la file de traitement',result.error?'error':'success')}
  return <div style={{height:'100%',display:'flex',flexDirection:'column',background:'var(--s1)'}}>
    <div style={{padding:'15px 18px',borderBottom:'1px solid var(--border)',display:'flex',justifyContent:'space-between',gap:12,alignItems:'flex-start'}}><div><button onClick={onClose} style={{background:'none',border:0,color:'var(--muted)',fontSize:11,cursor:'pointer',padding:0,marginBottom:7}}>← Retour aux prospects</button><h2 style={{fontFamily:'var(--serif)',fontSize:21,fontWeight:400}}>{prospect.name}</h2><div style={{fontSize:11,color:'var(--muted)',marginTop:4}}>{prospect.city||'Ville inconnue'} · {prospect.status}</div></div><Button variant="primary" size="sm" onClick={analyze} loading={analyzing}>Analyser</Button></div>
    <div role="tablist" aria-label="Fiche prospect" style={{display:'flex',gap:2,padding:'0 12px',borderBottom:'1px solid var(--border)',overflowX:'auto'}}>{TABS.map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)} style={{border:0,borderBottom:`2px solid ${tab===id?'var(--red)':'transparent'}`,background:'transparent',color:tab===id?'var(--text)':'var(--muted)',fontSize:11,fontFamily:'var(--sans)',padding:'10px 8px',cursor:'pointer',whiteSpace:'nowrap'}}>{label}</button>)}</div>
    <div style={{flex:1,overflowY:'auto',padding:mobile?'16px 14px':'20px'}}>{tab==='summary'&&<>
      <SectionCard><SectionTitle>Score et prochaine action</SectionTitle><div style={{display:'flex',gap:20,alignItems:'center',flexWrap:'wrap'}}><div style={{fontSize:28,fontWeight:700,color:prospect.score==null?'var(--muted2)':'var(--text)'}}>{prospect.score==null?'—':`${prospect.score}/100`}</div><div style={{flex:1,minWidth:180,fontSize:12,color:'var(--muted)',lineHeight:1.65}}>{prospect.score_reasons?.length?prospect.score_reasons.map(reason=><div key={reason}>• {reason}</div>):'Ce prospect n’a pas encore été scoré.'}</div></div></SectionCard>
      <SectionCard><SectionTitle>Identité et contact</SectionTitle><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(185px,1fr))',gap:'0 12px'}}>{EDIT.filter(key=>key!=='description').map(key=><Input key={key} label={fieldLabel[key]} value={form[key]??''} onChange={e=>set(key,e.target.value)}/>)}</div><Input label="Description" multiline value={form.description??''} onChange={e=>set('description',e.target.value)}/><div style={{display:'flex',justifyContent:'flex-end'}}><Button variant="primary" onClick={saveIdentity} loading={saving}>Sauvegarder la fiche</Button></div></SectionCard></>}
      {tab==='analysis'&&<JsonPanel title="Analyse validée" value={prospect.analysis} empty="Aucune analyse disponible."/>}
      {tab==='presence'&&<SectionCard><SectionTitle>Sources vérifiées</SectionTitle>{loading?<Muted>Chargement…</Muted>:related.sources.length?related.sources.map(source=><div key={source.id} style={item}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><strong>{source.type}</strong><span style={{color:'var(--muted2)',fontSize:10}}>{new Date(source.fetched_at).toLocaleDateString('fr-FR')}</span></div>{source.url&&<a href={source.url} target="_blank" rel="noreferrer" style={{display:'block',color:'var(--blue)',fontSize:11,margin:'5px 0',wordBreak:'break-all'}}>{source.url}</a>}<div style={{color:'var(--muted)',fontSize:11,lineHeight:1.55}}>{source.content_excerpt||'Aucun extrait textuel.'}</div></div>):<Muted>Aucune source enregistrée.</Muted>}</SectionCard>}
      {tab==='opportunities'&&<JsonPanel title="Angles commerciaux" value={prospect.strategy} empty="Aucune stratégie disponible."/>}
      {tab==='messages'&&<SectionCard><SectionTitle>Brouillons</SectionTitle>{loading?<Muted>Chargement…</Muted>:related.messages.length?related.messages.map(message=><div key={message.id} style={item}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><strong>{message.channel}</strong><span style={{fontSize:10,color:'var(--muted)'}}>{message.status} · révision {message.revision}</span></div>{message.subject&&<div style={{marginTop:8,fontWeight:600}}>{message.subject}</div>}<div style={{whiteSpace:'pre-wrap',fontSize:12,color:'var(--muted)',lineHeight:1.6,marginTop:6}}>{message.body}</div><div style={{fontSize:10,color:'var(--muted2)',marginTop:8}}>{message.sources_used?.length??0} source(s) utilisée(s)</div></div>):<Muted>Aucun message généré.</Muted>}</SectionCard>}
      {tab==='history'&&<SectionCard><SectionTitle>Historique</SectionTitle>{loading?<Muted>Chargement…</Muted>:related.events.length?related.events.map(event=><div key={event.id} style={{display:'grid',gridTemplateColumns:'110px 1fr',gap:12,padding:'9px 0',borderBottom:'1px solid var(--border)',fontSize:11}}><span style={{color:'var(--muted2)'}}>{new Date(event.created_at).toLocaleString('fr-FR')}</span><span><strong>{event.label||event.type}</strong><span style={{color:'var(--muted)',marginLeft:7}}>{event.actor==='user'?'Utilisateur':'Système'}</span></span></div>):<Muted>Aucun événement.</Muted>}</SectionCard>}
      {tab==='notes'&&<SectionCard><SectionTitle>Notes internes</SectionTitle><Input multiline rows={9} value={form.notes??''} onChange={e=>set('notes',e.target.value)} placeholder="Contexte utile, prochain échange…"/><Input label="Tags — séparés par des virgules" value={(form.tags??[]).join(', ')} onChange={e=>set('tags',e.target.value.split(',').map(value=>value.trim()).filter(Boolean))}/><div style={{display:'flex',justifyContent:'flex-end'}}><Button variant="primary" onClick={()=>save({notes:form.notes||null,tags:form.tags})} loading={saving}>Sauvegarder les notes</Button></div></SectionCard>}
    </div>
  </div>
}
const item={padding:'11px 0',borderBottom:'1px solid var(--border)',fontSize:12}
function Muted({children}){return <div style={{fontSize:12,color:'var(--muted)',padding:'12px 0'}}>{children}</div>}
function JsonPanel({title,value,empty}){return <SectionCard><SectionTitle>{title}</SectionTitle>{value?<pre style={{whiteSpace:'pre-wrap',wordBreak:'break-word',fontFamily:'var(--sans)',fontSize:12,lineHeight:1.65,color:'var(--muted)'}}>{JSON.stringify(value,null,2)}</pre>:<Muted>{empty}</Muted>}</SectionCard>}
